---
title: "TT_07_oregon_spotted_frog_script"
author: "Kenta"
date: "2023-05-05"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

# Loading Library

```{r}
library(tidyverse)
library(here)
library(tidytuesdayR)
library(ggplot2)
library(png)
library(patchwork)
```

# Viewing the Data

```{r}

frogs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-02/frogs.csv')

view(frogs)
```

# Creating a Clean Data

```{r}
clean_frogs <- frogs%>%
  drop_na()%>%
  select(Female, Water)
  

  
view(clean_frogs)
```

# # Creating a Plot for Mean and Standard Deviation for UTM Coordinate 

```{r}
plot_frog_female <- clean_frogs%>%
   ggplot(aes(x= Water, y= Female == 1, color = Female))+
  geom_col()+
  labs(title = "Females Surviving in the Wild",
       x = "Water field",
       y = "Number of Oregon Frogs",
       fill = "Group") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 0.5))
  theme_bw()

plot_frog_male <- clean_frogs%>%
   ggplot(aes(x= Water, y= Female == 0, color = Female))+
  geom_col()+
  labs(title = "Males Surviving in the Wild",
       x = "Water field",
       y = "Number of Oregon Frogs",
       fill = "Group") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 0.5))
  theme_bw()

plot_frog_female+plot_frog_male
```

