---
title: "TT_06_Ph.D._Awarded"
author: "Kenta"
date: "2023-04-25"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

# Loading Library

```{r}
library(tidyverse)
library(here)
library(tidytuesdayR)
library(ggplot2)
library(png)
library(magick)
```

# Viewing the Data

```{r}
phd_field <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-19/phd_by_field.csv")

bio_image <- readPNG(here("TT_06", "data", "Biology-1200x628-1.png"))

view(bio_image)

view(phd_field)
```

# Creating a Clean Data

```{r}
phd_field_clean <- phd_field%>%
  drop_na()%>%
  filter(major_field == "Biological and biomedical sciences")%>%
  group_by(year)%>%
  summarise_if(is.numeric, sum)
  selected_years <- c(2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017)

phd_field_clean_revised <- phd_field_clean%>%
  filter(year %in% selected_years)
  
view(phd_field_clean_revised)
```

# Creating a Plot for Biological and Biomedical Science by year

```{r}
biological_by_year_graph <- phd_field_clean_revised%>%
  ggplot(aes(x= year, y= n_phds, color = "Biological and Biomedical Science"))+
  geom_line()+
  scale_x_continuous(breaks = seq(2008, 2017, 1))+
  labs(title = "Biological and Biomedical Science Ph.D. by Year",
       x = "Years Achieved",
       y = "How Many Achieved")+
  theme(panel.grid.major = element_blank(),
        rect = bio_image)+
  scale_fill_gradient(low = "blue", high = "red")+
  theme_bw()
  

biological_by_year_graph
```


